FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
gns3-server \
ubridge \
dynamips \
vpcs \
qemu-system \
bridge-utils \
iproute2 \
iptables \
dnsmasq-base \
libpcap-dev \
python3 \
python3-pip \
curl \
&& apt clean

# Give ubridge permissions
RUN setcap cap_net_admin,cap_net_raw+ep /usr/bin/ubridge

EXPOSE 3080

CMD ["gns3server", "--host", "0.0.0.0", "--port", "3080"]
